### ISSUE TITLE
请问一下，TinaX.VFS 有没有方法获取一个文件夹下的所有文件的名称？

### ISSUE THREAD

**Issue by magicskysword** [yomunsam/TinaX#12]
我想要按照文件夹去读取和执行lua文件，但是现在只能一个个Require，当lua文件多了后看起来十分的乱......

**Comment by yomunsam** [comment]
讲真我觉得这个做法是有点问题的，所以设计时没有直接给出这样的功能，

然后应该是可以通过一定修改来实现这样功能，我回去研究下看看
