### ISSUE TITLE
啥时候添加网络功能

### ISSUE THREAD

**Issue by zhanjunxiong** [yomunsam/TinaX#7]
rt

**Comment by yomunsam** [comment]
这个framework里不会加入网络的功能。

目前有在做一个独立的网络模块，可以与TinaX配合，也可以单独使用。目前正在内部项目中尝试使用并完善它。

**Comment by zhanjunxiong** [comment]
这个独立的网络模块是否考虑开源？

**Comment by yomunsam** [comment]
有这方面计划，但需要时间
