### ISSUE TITLE
[BUG] 在IL2CPP模式下启动游戏有一定几率卡死

### ISSUE THREAD

**Issue by yomunsam** [yomunsam/TinaX#8]
### Bug描述

TinaX6.5.x预览版本，
使用IL2CPP方式构建的真机包中，有一定几率在启动时卡死，不会触发任何业务逻辑层面的入口代码。

在Android、iOS平台复现必现，UWP IL2CPP不会触发bug

**Comment by yomunsam** [comment]
![image](https://user-images.githubusercontent.com/24813704/67725171-5db9d980-fa1c-11e9-8e55-2facac41cb2b.png)

发现问题在重构后的虚拟文件系统功能，图示部分。

该部分在IL2CPP下直接运行时卡死，（而且比较气人的是，如果对它打断点，单步跟踪调试的话，它反而一点问题都没有，你们都想不到我是怎么发现这个地方有问题的）

然后把这个方法拆开，
![image](https://user-images.githubusercontent.com/24813704/67725291-cc973280-fa1c-11e9-9c72-5e4da0d39f03.png)

运行起来就没毛病了，

至于具体是Unity的锅还是.NET的锅还是Unirx的锅，还没细研究

**Comment by yomunsam** [comment]
好像还有点残余的问题

**Comment by GlodenBoy** [comment]
这个问题有彻底解决吗？

**Comment by yomunsam** [comment]
> 这个问题有彻底解决吗？

好了

**Comment by GlodenBoy** [comment]
> > 这个问题有彻底解决吗？
> 
> 好了

老哥，这个项目只是自己在学习开发的，还是实际上由成熟产品上线了？

**Comment by yomunsam** [comment]
> > > 这个问题有彻底解决吗？
> > 
> > 
> > 好了
> 
> 老哥，这个项目只是自己在学习开发的，还是实际上由成熟产品上线了？

这个主要是我平时接外快项目时候用的，至于成不成熟我也不知道（逃

目前也有些开发者在用它

**Comment by GlodenBoy** [comment]
> > > > 这个问题有彻底解决吗？
> > > 
> > > 
> > > 好了
> > 
> > 
> > 老哥，这个项目只是自己在学习开发的，还是实际上由成熟产品上线了？
> 
> 这个主要是我平时接外快项目时候用的，至于成不成熟我也不知道（逃
> 
> 目前也有些开发者在用它

我也是入门unity没多久，自己家的老项目过于庞大，想找一个轻量适合扩展学习的然后一直用下去的。辗转搜到了老哥的项目，有文档，结构也挺清晰的，希望老哥能一直维护下去😅
