### ISSUE TITLE
是否 可以支持 lua 文件 去掉.txt 后缀

### ISSUE THREAD

**Issue by cloudfreexiao** [yomunsam/TinaX#9]
我看 项目中有 转 后缀的脚本 但是在实际开发中 一般都会配合 luacheck 之类的🚌 
txt 后缀 有点不太好处理这些

**Comment by yomunsam** [comment]
这主要是，.lua的后缀Unity不认识，所以还是推荐.lua.txt后缀
（luacheck可以设置后缀的呀）

**Comment by yomunsam** [comment]
设置里可以设置成.lua后缀，不过这时候unity不认识它，没法拖给luaBehaviour用
